local lume = require("lib.lume")
local raylib = {}
local colors = require("lib.colors")
local window = require("lib.window")
local structs = require("lib.structs")
local cursor = require("lib.cursor")
local raudio = require("lib.raudio")
local rmodels = require("lib.rmodels")
local rtext = require("lib.rtext")
local rtextures = require("lib.rtextures")
local rshapes = require("lib.rshapes")
local drawing = require("lib.drawing")
local inputhandling = require("lib.inputhandling")
local enumerators = require("lib.enumerators")
local utils = require("lib.utils")
utils["merge-tables"](raylib, colors)
utils["merge-tables"](raylib, window)
utils["merge-tables"](raylib, structs)
utils["merge-tables"](raylib, cursor)
utils["merge-tables"](raylib, raudio)
utils["merge-tables"](raylib, rmodels)
utils["merge-tables"](raylib, rtext)
utils["merge-tables"](raylib, rtextures)
utils["merge-tables"](raylib, rshapes)
utils["merge-tables"](raylib, drawing)
utils["merge-tables"](raylib, inputhandling)
utils["merge-tables"](raylib, enumerators)
return raylib
